services:
  - type: web
    name: identity-catalog-service
    env: node
    plan: free
    rootDir: identity-catalog-service
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4001
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: INTERNAL_SERVICE_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
      - key: RATE_LIMIT_PUBLIC_MAX
        value: "100"
      - key: RATE_LIMIT_AUTH_MAX
        value: "5"
      - key: RATE_LIMIT_AUTH_MAX_CONSECUTIVE_FAILS
        value: "5"
      - key: RATE_LIMIT_USER_MAX
        value: "200"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false

  - type: web
    name: commerce-order-service
    env: node
    plan: free
    rootDir: commerce-order-service
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4002
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: INTERNAL_SERVICE_KEY
        sync: false
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
      - key: RATE_LIMIT_PUBLIC_MAX
        value: "100"
      - key: RATE_LIMIT_AUTH_MAX
        value: "5"
      - key: RATE_LIMIT_AUTH_MAX_CONSECUTIVE_FAILS
        value: "5"
      - key: RATE_LIMIT_USER_MAX
        value: "200"
